### PR TITLE
discord 1.0.9020

### PR DESCRIPTION
**Pull request by wharlox**

### CODE REVIEW

**Comment by wharlox** [comment]
im not sure if the `assets/assets.go` gets created via git-actions ; (but to be frank im 1/2 asleep and missed the merge request targeting to here vs my own fork)

**Comment by kossnikita** [comment]
Works good for me! Thanks!

**Comment by lawayne** [comment]
how can I get your version of the build? are you able to distribute a release or must we build it ourselves? where can I read up on how to build your version of the app? I'm afraid I'm unfamiliar with the process 😬

**Comment by kossnikita** [comment]
It can be accessed in [Actions Artifacts](https://github.com/wharlox/portapps__discord-portable/actions/runs/6650978664)
Please do not take this as an official release. Do not report bugs in this version to this repository.

**Comment by lawayne** [comment]
thanks a bunch! not another peep from me in these parts, chief 🤐

**Comment by wharlox** [comment]
fyi i updated the build with that `assets/assets.go` file included (not sure of its significance to be quite honest); i deleted the first build @kossnikita  linked to; and yes, do not take it as an official release - we'll wait for the maintainer to handle that. 

can be tested from:
https://github.com/wharlox/portapps__discord-portable/actions or directly to the run https://github.com/wharlox/portapps__discord-portable/actions/runs/6662367990

**Comment by dystopia2017** [comment]
Thank you very much, your fix works great :)

**Comment by crazy-max** [comment]
Sorry for the delay, made some changes to update to 1.0.9022 in #112 
@wharlox Update instructions in build properties is a bit confusing. Reloading assets is not necessary actually.

**Comment by wharlox** [comment]
> @wharlox Update instructions in build properties are a bit confusing. Reloading assets is not necessary actually.

ah cool good to know for next time; was a fun little exercise nonetheless; appreciate the whole automated workflow setup here

**Pull request closed without merging**
